# Generated by Django 4.1.1 on 2022-11-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_service', '0002_user_groups_user_is_staff_user_is_superuser_and_more'),
        ('users_service', '0003_remove_user_groups_remove_user_is_superuser_and_more'),
    ]

    operations = [
    ]
