# Generated by Django 4.1.1 on 2022-11-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productonsale',
            old_name='stock_id',
            new_name='stock',
        ),
    ]
