# Generated by Django 4.1.1 on 2022-09-28 21:46

from django.db import migrations, models
import django.db.models.deletion
import orders_service.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('product_id', models.UUIDField()),
            ],
            options={
                'unique_together': {('id', 'user_id', 'product_id')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(default=orders_service.models.gen_big_int, unique=True)),
                ('user_id', models.UUIDField()),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_service.deliverymethod')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_service.paymethod')),
                ('product_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders_service.productset')),
            ],
        ),
    ]
