# Generated by Django 4.1.1 on 2022-11-23 19:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productset',
            name='product_set_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='productset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
