# Generated by Django 4.1.1 on 2022-11-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_service', '0002_productset_product_set_id_alter_productset_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_set',
            field=models.UUIDField(unique=True),
        ),
    ]
