# Generated by Django 4.1.1 on 2022-11-30 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders_service', '0003_alter_order_product_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productset',
            name='product_set_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
