# Generated by Django 4.1.1 on 2022-09-28 21:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_service.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.TextField(max_length=255)),
                ('name', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('characteristics', models.JSONField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_service.category')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_service.type')),
            ],
        ),
    ]
