# Generated by Django 4.1.1 on 2022-10-25 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.TextField(max_length=30),
        ),
    ]
