# Generated by Django 4.1.1 on 2022-11-17 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_service', '0003_alter_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='category',
        ),
    ]
