# Generated by Django 4.1.1 on 2022-12-04 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file_id', models.TextField()),
                ('type', models.TextField(max_length=20)),
                ('source_id', models.UUIDField()),
            ],
            options={
                'unique_together': {('id', 'source_id')},
            },
        ),
    ]
