# Generated by Django 4.1.1 on 2022-09-28 21:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.TextField(max_length=30)),
                ('size', models.IntegerField()),
                ('path', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.TextField(max_length=30)),
                ('source_id', models.UUIDField()),
                ('source_type', models.TextField(max_length=30)),
                ('media_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attachments_service.media')),
            ],
        ),
    ]
