# Generated by Django 4.1.1 on 2022-12-04 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attachment',
            unique_together={('file_id', 'source_id')},
        ),
    ]
